//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ems.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmsResousrce {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmsResousrce() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ems.Services.EmsResousrce", typeof(EmsResousrce).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseUrl.
        /// </summary>
        public static string ConfigBaseUrl {
            get {
                return ResourceManager.GetString("ConfigBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLoginAttempt.
        /// </summary>
        public static string ConfigMaxLoginAttempt {
            get {
                return ResourceManager.GetString("ConfigMaxLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string DefaultCreatedBy {
            get {
                return ResourceManager.GetString("DefaultCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is already registered..
        /// </summary>
        public static string ErrMsgCompanyNameAlreadyExist {
            get {
                return ResourceManager.GetString("ErrMsgCompanyNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address is already use by other account.
        /// </summary>
        public static string ErrMsgEmailAddressAlreadyExist {
            get {
                return ResourceManager.GetString("ErrMsgEmailAddressAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum login attempt reach. Please Contact Administrator.
        /// </summary>
        public static string ErrMsgInvalidLoginAttempt {
            get {
                return ResourceManager.GetString("ErrMsgInvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password.
        /// </summary>
        public static string ErrMsgInvalidPassword {
            get {
                return ResourceManager.GetString("ErrMsgInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Token is not valid.
        /// </summary>
        public static string ErrMsgInvalidValidationToken {
            get {
                return ResourceManager.GetString("ErrMsgInvalidValidationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name not found.
        /// </summary>
        public static string ErrMsgNoUserFound {
            get {
                return ResourceManager.GetString("ErrMsgNoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exist.
        /// </summary>
        public static string ErrMsgUserNameAlreadyExist {
            get {
                return ResourceManager.GetString("ErrMsgUserNameAlreadyExist", resourceCulture);
            }
        }
    }
}
