//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ems.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityProfile : BaseEntity
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int AccessMenuId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool HasAccess { get; set; }
    
        public virtual AccessMenu AccessMenu { get; set; }
        public virtual Role Role { get; set; }
    }
}
